import AppKit
import Foundation

/// The small, main-actor isolated boundary used by Clipboard History.
///
/// Keeping this protocol separate from ``NSPasteboard`` means the monitor can
/// be tested without ever touching the user's general pasteboard.  In
/// particular, reading ``changeCount`` is itself an access that callers should
/// only perform after the user has enabled Clipboard History.
@MainActor
protocol PasteboardAccess {
    var changeCount: Int { get }

    /// Reads one normalized, allow-listed payload, or nil when the current
    /// pasteboard item is unsupported, sensitive, malformed, or over a limit.
    func readPayload() -> ClipboardPayload?

    /// Replaces the general pasteboard with a payload explicitly selected by
    /// the user.  The returned value is the pasteboard's change count after a
    /// successful write.
    @discardableResult
    func write(_ payload: ClipboardPayload) -> Int?
}

/// The production pasteboard adapter.  All content handling lives here so the
/// monitor only coordinates change-count polling and never logs or persists
/// pasteboard data.
@MainActor
final class GeneralPasteboardAccess: PasteboardAccess {
    static let maximumTextUTF8Bytes = 50_000
    /// The product plan deliberately uses a conservative 10 MiB per-image
    /// bound.  Oversized data is rejected before it can become a history item.
    static let maximumImageBytes = 10 * 1024 * 1024
    static let maximumFileURLCount = 20

    private static let textTypes: [NSPasteboard.PasteboardType] = [
        .string,
        NSPasteboard.PasteboardType(rawValue: "NSStringPboardType"),
        NSPasteboard.PasteboardType(rawValue: "public.plain-text"),
    ]

    private static let imageTypes: [NSPasteboard.PasteboardType] = [
        .png,
        .tiff,
        NSPasteboard.PasteboardType(rawValue: "public.jpeg"),
    ]

    private static let fileURLTypes: [NSPasteboard.PasteboardType] = [
        .fileURL,
        NSPasteboard.PasteboardType(rawValue: "public.file-url"),
        NSPasteboard.PasteboardType(rawValue: "NSFilenamesPboardType"),
    ]

    /// Markers emitted by AppKit, password managers, and common secret
    /// providers.  The list intentionally errs on the side of rejecting a
    /// value; it cannot identify every third-party secret representation.
    private static let sensitiveTypeMarkers = [
        "concealed",
        "transient",
        "autogenerated",
        "auto-generated",
        "password",
        "secret",
        "credential",
        "token",
        "privatekey",
        "private-key",
        "keychain",
        "onepassword",
        "1password",
        "lastpass",
        "bitwarden",
        "keepass",
    ]

    private let pasteboard: NSPasteboard

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    var changeCount: Int {
        pasteboard.changeCount
    }

    var accessBehavior: NSPasteboard.AccessBehavior {
        pasteboard.accessBehavior
    }

    func readPayload() -> ClipboardPayload? {
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else {
            return nil
        }

        let declaredTypes = items.flatMap(\.types).map(\.rawValue)
        guard let payloadKind = Self.preferredPayloadKind(
            forDeclaredTypeIdentifiers: declaredTypes
        ) else { return nil }

        // One pasteboard change produces exactly one history payload. Apply
        // the documented priority across all declared items.
        switch payloadKind {
        case .fileURLs:
            return readFileURLs()
        case .image:
            guard let imageType = Self.firstType(items, from: Self.imageTypes) else {
                return nil
            }
            return readImage(type: imageType)
        case .text:
            guard let textType = Self.firstType(items, from: Self.textTypes) else {
                return nil
            }
            return readText(type: textType)
        }
    }

    @discardableResult
    func write(_ payload: ClipboardPayload) -> Int? {
        let didWrite: Bool
        switch payload {
        case .text(let text):
            guard let data = text.data(using: .utf8),
                  !data.isEmpty,
                  data.count <= Self.maximumTextUTF8Bytes else {
                return nil
            }
            _ = pasteboard.clearContents()
            didWrite = pasteboard.setString(text, forType: .string)

        case .image(let data, let mimeType):
            guard !data.isEmpty, data.count <= Self.maximumImageBytes else {
                return nil
            }
            let type: NSPasteboard.PasteboardType
            switch mimeType.lowercased() {
            case "image/png":
                type = .png
            case "image/tiff", "image/tif":
                type = .tiff
            case "image/jpeg", "image/jpg":
                type = NSPasteboard.PasteboardType(rawValue: "public.jpeg")
            default:
                return nil
            }
            _ = pasteboard.clearContents()
            didWrite = pasteboard.setData(data, forType: type)

        case .fileURLs(let urls):
            guard !urls.isEmpty,
                  urls.count <= Self.maximumFileURLCount,
                  urls.allSatisfy({ $0.isFileURL && !$0.path.isEmpty }) else {
                return nil
            }
            _ = pasteboard.clearContents()
            let writingURLs: [NSPasteboardWriting] = urls.map { $0 as NSURL }
            didWrite = pasteboard.writeObjects(writingURLs)
        }

        return didWrite ? pasteboard.changeCount : nil
    }

    private func readFileURLs() -> ClipboardPayload? {
        let objects = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) ?? []
        let urls = objects.compactMap { object -> URL? in
            guard let url = object as? NSURL else { return nil }
            let candidate = url as URL
            guard candidate.isFileURL, !candidate.path.isEmpty else {
                return nil
            }
            return candidate.standardizedFileURL
        }

        guard !urls.isEmpty,
              urls.count <= Self.maximumFileURLCount,
              urls.count == objects.count else {
            return nil
        }
        return .fileURLs(urls)
    }

    private func readImage(
        type: NSPasteboard.PasteboardType
    ) -> ClipboardPayload? {
        guard let item = pasteboard.pasteboardItems?.first(where: {
            $0.types.contains(type)
        }),
        let data = item.data(forType: type),
        !data.isEmpty,
        data.count <= Self.maximumImageBytes else {
            return nil
        }

        let mimeType: String
        switch type.rawValue {
        case NSPasteboard.PasteboardType.png.rawValue:
            mimeType = "image/png"
        case "public.jpeg":
            mimeType = "image/jpeg"
        default:
            mimeType = "image/tiff"
        }
        return .image(data: data, mimeType: mimeType)
    }

    private func readText(
        type: NSPasteboard.PasteboardType
    ) -> ClipboardPayload? {
        guard let item = pasteboard.pasteboardItems?.first(where: {
            $0.types.contains(type)
        }) else {
            return nil
        }

        guard let text = item.string(forType: type),
              let utf8 = text.data(using: .utf8),
              !utf8.isEmpty,
              utf8.count <= Self.maximumTextUTF8Bytes,
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return nil
        }
        return .text(text)
    }

    private static func firstType(
        _ items: [NSPasteboardItem],
        from candidates: [NSPasteboard.PasteboardType]
    ) -> NSPasteboard.PasteboardType? {
        for candidate in candidates {
            if items.contains(where: { $0.types.contains(candidate) }) {
                return candidate
            }
        }
        return nil
    }

    static func preferredPayloadKind(
        forDeclaredTypeIdentifiers identifiers: [String]
    ) -> ClipboardPayload.Kind? {
        guard !identifiers.contains(where: isSensitiveTypeIdentifier) else {
            return nil
        }
        let declared = Set(identifiers)
        if fileURLTypes.contains(where: { declared.contains($0.rawValue) }) {
            return .fileURLs
        }
        if imageTypes.contains(where: { declared.contains($0.rawValue) }) {
            return .image
        }
        if textTypes.contains(where: { declared.contains($0.rawValue) }) {
            return .text
        }
        return nil
    }

    static func isSensitiveTypeIdentifier(_ identifier: String) -> Bool {
        let raw = identifier.lowercased()
        return sensitiveTypeMarkers.contains(where: raw.contains)
    }
}
